export const MiraDesign = {
  color: {
    canvas: '#F4F9FA',
    surface: '#FFFFFF',
    surfaceStrong: '#FFFFFF',
    surfaceSoft: '#ECF6F7',
    surfaceTint: '#E5F5F2',
    ink: '#12343B',
    inkSoft: '#587177',
    muted: '#8CA3A8',
    line: '#D8E8EA',
    primary: '#0EA5A4',
    primaryDeep: '#087B7A',
    primarySoft: '#DDF5F3',
    blue: '#3278C7',
    blueSoft: '#E6F0FB',
    mint: '#54CFA5',
    amber: '#F5B84B',
    coral: '#EE6B6E',
    danger: '#EE6B6E',
    lavender: '#8D7EF5',
    showcaseCanvas: '#EAF6FF',
    showcaseCanvasDeep: '#D7ECFF',
    showcaseSurface: '#F9FDFF',
    showcaseNavy: '#071D49',
    showcaseNavySoft: '#385780',
    showcaseBlue: '#176BFF',
    showcaseBlueDeep: '#0A3A9E',
    showcaseBlueSoft: '#DDEEFF',
    showcaseCyan: '#65D8FF',
    showcaseLine: '#C6E0FA',
    showcaseLineSoft: '#D1E7FF',
    showcaseMint: '#18B883',
  },
  radius: {
    xs: 6,
    sm: 8,
    md: 14,
    lg: 22,
    pill: 999,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 28,
  },
};

export const shadow = {
  shadowColor: '#7FADE8',
  shadowOffset: { width: 0, height: 10 },
  shadowOpacity: 0.14,
  shadowRadius: 20,
  elevation: 7,
};

export const softShadow = {
  shadowColor: '#9EBFE8',
  shadowOffset: { width: 0, height: 6 },
  shadowOpacity: 0.08,
  shadowRadius: 16,
  elevation: 3,
};
