// PKM-Shop — catalog management (products + categories). Role: stock or admin.
// Owner directive 2026-07-14: adding a product must Just Work for a non-technical shop owner.
//  - catalog_key is auto-generated by the DB trigger from the name (no manual code field).
//  - a category can be created inline (create_category) so the product form never dead-ends.
//  - product photo is uploaded here (base64 -> service-role storage write), so ANY catalog
//    role can attach an image without hitting the admin-only storage policy.
//  - NO weight, NO per-product commission (commission is the shop-wide setting).
// All writes run with the service role (RLS bypassed) AFTER the staff role is verified, so
// the fragile direct-from-browser insert that used to fail silently is gone.
import { assertTenant, insertRow, selectOne, updateRows } from '../_shared/db.ts';
import { handleOptions, HttpError, json, toErrorResponse, validateJson, z } from '../_shared/http.ts';
import { assertRole, resolveStaffProfile } from '../_shared/pkmAuth.ts';
import { uploadStorageObject } from '../_shared/storage.ts';

declare const Deno: {
  serve: (handler: (req: Request) => Response | Promise<Response>) => void;
};

const IMAGE = z.object({ image_base64: z.string().min(1), content_type: z.enum(['image/jpeg', 'image/png', 'image/webp']) });

const schema = z.discriminatedUnion('action', [
  z.object({ action: z.literal('create_category'), tenant_slug: z.string().min(1), name: z.string().trim().min(1).max(60), sort: z.number().int().min(0).max(9999).optional() }),
  z.object({ action: z.literal('update_category'), tenant_slug: z.string().min(1), category_id: z.string().uuid(), name: z.string().trim().min(1).max(60).optional(), sort: z.number().int().min(0).max(9999).optional(), active: z.boolean().optional() }),
  z.object({
    action: z.literal('create_product'), tenant_slug: z.string().min(1),
    name: z.string().trim().min(1).max(120),
    price_baht: z.number().int().min(0).max(10_000_000),
    category_id: z.string().uuid().nullable().optional(),
    description: z.string().max(500).optional(),
    image: IMAGE.optional(),
  }),
  z.object({
    action: z.literal('update_product'), tenant_slug: z.string().min(1), product_id: z.string().uuid(),
    name: z.string().trim().min(1).max(120).optional(),
    price_baht: z.number().int().min(0).max(10_000_000).optional(),
    category_id: z.string().uuid().nullable().optional(),
    description: z.string().max(500).optional(),
    active: z.boolean().optional(),
    image: IMAGE.optional(),
  }),
]);

const PRODUCT_SELECT = 'id,catalog_key,name,description,price_baht,category_id,category,image_url,stock_qty,reserved_qty,active';
const CATEGORY_SELECT = 'id,name,sort,active';

type CategoryRow = { id: string; name: string; sort: number; active: boolean };

function decodeBase64(b64: string): Uint8Array {
  const clean = b64.includes(',') ? b64.slice(b64.indexOf(',') + 1) : b64; // tolerate data: URLs
  const binary = atob(clean);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

const EXT: Record<string, string> = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' };

// Store the product photo on the public product-images bucket, foldered by tenant slug.
async function storeImage(tenantSlug: string, image: { image_base64: string; content_type: string }): Promise<string> {
  const bytes = decodeBase64(image.image_base64);
  if (bytes.byteLength > 5_000_000) throw new HttpError('VALIDATION', 'รูปใหญ่เกินไป (เกิน 5MB)', 400);
  const path = `${tenantSlug}/${crypto.randomUUID()}.${EXT[image.content_type] ?? 'jpg'}`;
  return uploadStorageObject('product-images', path, bytes, image.content_type);
}

async function categoryName(tenantId: string, categoryId: string | null | undefined): Promise<string> {
  if (!categoryId) return 'general';
  const cat = await selectOne<CategoryRow>('categories', { id: `eq.${categoryId}`, select: CATEGORY_SELECT, tenant_id: `eq.${tenantId}` });
  return cat?.name ?? 'general';
}

Deno.serve(async (req) => {
  const optionsResponse = handleOptions(req);
  if (optionsResponse) return optionsResponse;
  try {
    const body = await validateJson(req, schema);
    const tenant = await assertTenant(body.tenant_slug);
    const profile = await resolveStaffProfile(req.headers.get('authorization'), tenant.id);
    assertRole(profile, ['stock']); // admin passes via assertRole's admin bypass

    switch (body.action) {
      case 'create_category': {
        const row = await insertRow<CategoryRow>('categories', {
          tenant_id: tenant.id, name: body.name, sort: body.sort ?? 100,
        }, { select: CATEGORY_SELECT });
        return json({ ok: true, category: row });
      }
      case 'update_category': {
        const patch: Record<string, unknown> = {};
        if (body.name !== undefined) patch.name = body.name;
        if (body.sort !== undefined) patch.sort = body.sort;
        if (body.active !== undefined) patch.active = body.active;
        const rows = await updateRows<CategoryRow>('categories', patch, { id: `eq.${body.category_id}`, tenant_id: `eq.${tenant.id}`, select: CATEGORY_SELECT });
        if (!rows[0]) throw new HttpError('VALIDATION', 'ไม่พบหมวดสินค้า', 404);
        return json({ ok: true, category: rows[0] });
      }
      case 'create_product': {
        const image_url = body.image ? await storeImage(tenant.slug, body.image) : null;
        const row = await insertRow('products', {
          tenant_id: tenant.id,
          name: body.name,
          price_baht: body.price_baht,
          description: body.description ?? '',
          category_id: body.category_id ?? null,
          category: await categoryName(tenant.id, body.category_id ?? null),
          image_url,
          // catalog_key intentionally omitted -> trigger derives it from the name.
        }, { select: PRODUCT_SELECT });
        return json({ ok: true, product: row });
      }
      case 'update_product': {
        const patch: Record<string, unknown> = { updated_at: new Date().toISOString() };
        if (body.name !== undefined) patch.name = body.name;
        if (body.price_baht !== undefined) patch.price_baht = body.price_baht;
        if (body.description !== undefined) patch.description = body.description;
        if (body.active !== undefined) patch.active = body.active;
        if (body.category_id !== undefined) {
          patch.category_id = body.category_id;
          patch.category = await categoryName(tenant.id, body.category_id);
        }
        if (body.image) patch.image_url = await storeImage(tenant.slug, body.image);
        const rows = await updateRows('products', patch, { id: `eq.${body.product_id}`, tenant_id: `eq.${tenant.id}`, select: PRODUCT_SELECT });
        if (!rows[0]) throw new HttpError('VALIDATION', 'ไม่พบสินค้า', 404);
        return json({ ok: true, product: rows[0] });
      }
      default:
        throw new HttpError('VALIDATION', 'Unknown action.', 400);
    }
  } catch (error) {
    return toErrorResponse(error);
  }
});
