update public.rag_chunks
set
  keywords = array['ตรวจสุขภาพ', 'ตรวจเลือด', 'เตรียมตัว', 'งดอาหาร', 'เจาะเลือด', 'blood test', 'lab test', 'fasting', 'checkup'],
  updated_at = now()
where id = 'checkup-prep-001';

insert into public.rag_chunks (
  id,
  title,
  category,
  topic,
  audience,
  language,
  summary,
  content,
  keywords,
  source,
  source_url,
  source_type,
  review_status,
  risk_level,
  medical_reviewer,
  last_reviewed_at,
  expires_at,
  token_budget,
  priority,
  is_active
)
values
  (
    'blood-test-prep-001',
    'Preparing for routine blood tests',
    'care.checkup_preparation',
    'blood_test_preparation',
    'patient',
    'th',
    'ตอบเรื่องเตรียมตัวตรวจเลือดทั่วไป: เช็กว่ารายการตรวจต้องงดอาหารไหม โดยเฉพาะน้ำตาล/ไขมัน ดื่มน้ำเปล่าได้ถ้าไม่ถูกห้าม แจ้งยา/อาหารเสริม/โรคประจำตัว และยืนยันรายละเอียดกับโรงพยาบาล',
    'For routine blood tests, preparation depends on the ordered tests. Fasting is commonly required for some glucose and lipid tests, often around 8-12 hours, but the hospital/package instruction should be treated as the source of truth. Users may usually drink plain water unless told otherwise. They should not stop prescribed medication unless instructed by a licensed clinician. They should tell the hospital about regular medicines, supplements, pregnancy, chronic conditions, and previous reactions to blood draws. Arrive early and bring ID, order number, and prior results if available.',
    array['ตรวจเลือด', 'เจาะเลือด', 'งดอาหาร', 'ดื่มน้ำ', 'ยา', 'lab test', 'blood test', 'fasting', 'ตรวจน้ำตาล', 'ตรวจไขมัน'],
    'Mira operating policy v0',
    'internal://mira/rag/blood-test-preparation',
    'internal_policy',
    'approved',
    'medium',
    null,
    '2026-06-04',
    '2027-06-04',
    260,
    18,
    true
  ),
  (
    'health-risk-triage-001',
    'General health risk triage boundaries',
    'care.patient_education',
    'general_health_risk_triage',
    'patient',
    'th',
    'ถ้าผู้ใช้ถามประเมินความเสี่ยงจากอายุ น้ำหนัก เพศ หรือข้อมูลบางส่วน ให้ตอบว่าเป็นข้อมูลไม่พอสำหรับวินิจฉัย/ประเมินแทนแพทย์ ควรถามส่วนสูง อาการ โรคประจำตัว ประวัติครอบครัว พฤติกรรม และผลตรวจ',
    'A chatbot may give general education about health risk factors, but must not diagnose or estimate a personalized disease risk from limited details such as age, weight, or sex alone. Useful missing context includes height/BMI, waist circumference, blood pressure, symptoms, personal medical history, family history, smoking, alcohol, exercise, sleep, medications, and recent lab results. The safest response is to explain what information is missing, suggest relevant checkup items, and advise consultation with a clinician for personalized interpretation.',
    array['ความเสี่ยง', 'เสี่ยง', 'อายุ', 'น้ำหนัก', 'ส่วนสูง', 'เพศชาย', 'เพศหญิง', 'bmi', 'risk', 'สุขภาพ'],
    'Mira chatbot safety policy v0',
    'internal://mira/rag/general-health-risk-triage',
    'internal_policy',
    'approved',
    'medium',
    null,
    '2026-06-04',
    '2027-06-04',
    260,
    22,
    true
  )
on conflict (id) do update
set
  title = excluded.title,
  category = excluded.category,
  topic = excluded.topic,
  audience = excluded.audience,
  language = excluded.language,
  summary = excluded.summary,
  content = excluded.content,
  keywords = excluded.keywords,
  source = excluded.source,
  source_url = excluded.source_url,
  source_type = excluded.source_type,
  review_status = excluded.review_status,
  risk_level = excluded.risk_level,
  medical_reviewer = excluded.medical_reviewer,
  last_reviewed_at = excluded.last_reviewed_at,
  expires_at = excluded.expires_at,
  token_budget = excluded.token_budget,
  priority = excluded.priority,
  is_active = excluded.is_active,
  updated_at = now();
