with seed_products (
  id,
  mock_package_id,
  title,
  hospital_name,
  category,
  price_amount,
  duration,
  location,
  hospital_address,
  hospital_map_query,
  hospital_lat,
  hospital_lng,
  description,
  includes,
  tags,
  preparation_notes,
  booking_note,
  rag_chunk_id,
  preview_image_key,
  referral_rate
) as (
  values
    (
      'a0e1b2c3-d4f5-4261-9a01-010101010101'::uuid,
      'pkg_basic_blood',
      'Basic Blood Checkup',
      'Mira Partner Hospital',
      'lab_test',
      3500,
      '45-60 mins',
      'Bangkok',
      'Wireless Road Life Science Center, Bangkok',
      'Mira Partner Hospital Wireless Road Bangkok',
      13.7359,
      100.5471,
      'แพ็กเกจตรวจเลือดพื้นฐานสำหรับ baseline สุขภาพ รวม CBC, fasting blood sugar, HbA1c, lipid profile, liver และ kidney screen เหมาะกับผู้ใช้ที่ถามเรื่องตรวจเลือด เจาะเลือด เช็กน้ำตาล ไขมัน ตับ หรือไตแบบเริ่มต้น',
      array['CBC', 'Fasting blood sugar', 'HbA1c', 'Lipid profile', 'Liver and kidney screen'],
      array['Lab', 'Blood test', 'Popular', 'ตรวจเลือด', 'เจาะเลือด', 'CBC', 'HbA1c', 'lipid'],
      'ยืนยันเงื่อนไขงดอาหารกับโรงพยาบาลก่อนตรวจ โดยเฉพาะรายการน้ำตาลหรือไขมัน ดื่มน้ำเปล่าได้ถ้าโรงพยาบาลไม่ห้าม และนำผลตรวจเดิม/รายการยาไปด้วย',
      'หลังชำระเงิน ให้โทร call center พร้อมแจ้ง order number เพื่อเลือกวันและเวลานัดตรวจ',
      'mock-product-pkg-basic-blood-evidence',
      'blood',
      0.02
    ),
    (
      'b1f5a9e8-7f4c-4c64-a222-3c86d4e8a101'::uuid,
      'pkg_heart_metabolic',
      'Heart & Metabolic Advanced',
      'Aster International Hospital',
      'health_checkup',
      12900,
      '3-4 hours',
      'Bangkok',
      'Rama 9 Medical Campus, Bangkok',
      'Aster International Hospital Rama 9 Bangkok',
      13.7557,
      100.5654,
      'แพ็กเกจตรวจสุขภาพเชิงหัวใจและเมตาบอลิกสำหรับผู้ใช้ที่สนใจความเสี่ยงเบาหวาน ไขมัน หัวใจ metabolic syndrome หรือมีประวัติครอบครัว รวม CBC/chemistry panel, HbA1c/insulin resistance, lipid profile, ECG และ doctor summary',
      array['CBC and chemistry panel', 'HbA1c and insulin resistance', 'Lipid profile', 'ECG', 'Doctor summary'],
      array['Heart', 'Diabetes', 'Lipid', 'ECG', 'metabolic', 'หัวใจ', 'เบาหวาน', 'ไขมัน'],
      'ตรวจสอบเงื่อนไขงดอาหารกับโรงพยาบาล เพราะรายการน้ำตาล/ไขมันอาจต้องงดอาหาร เตรียมประวัติครอบครัว ยา อาหารเสริม และผลตรวจเดิมถ้ามี',
      'หลังชำระเงิน ให้โทร call center พร้อมแจ้ง order number เพื่อเลือกวันและเวลานัดตรวจ',
      'mock-product-pkg-heart-metabolic-evidence',
      'heart',
      0.03
    ),
    (
      'c2d9b6f3-8f1a-4e55-b333-4d97e5f9b202'::uuid,
      'pkg_cancer_baseline',
      'Cancer Risk Baseline',
      'Sukhumvit Wellness Center',
      'health_checkup',
      18900,
      'Half day',
      'Bangkok',
      'Sukhumvit 49 Health Plaza, Bangkok',
      'Sukhumvit Wellness Center Sukhumvit 49 Bangkok',
      13.7308,
      100.5755,
      'แพ็กเกจตั้งต้นสำหรับวางแผนคัดกรองความเสี่ยงมะเร็งประจำปี โดยเน้น doctor risk intake, core tumor markers, ultrasound abdomen และ lifestyle risk report พร้อมคำเตือนว่า tumor marker ไม่ใช่เครื่องมือคัดกรองทั่วไปสำหรับคนไม่มีอาการเสมอไป',
      array['Doctor risk intake', 'Core tumor markers', 'Ultrasound abdomen', 'Lifestyle risk report'],
      array['Tumor markers', 'Imaging', 'Family risk', 'มะเร็ง', 'คัดกรองมะเร็ง', 'ultrasound', 'อัลตราซาวด์'],
      'เตรียมประวัติครอบครัว ผลคัดกรองหรือ imaging เดิม อาการสำคัญ ยาที่ใช้ และยืนยันเงื่อนไขเตรียมตัว ultrasound กับโรงพยาบาล',
      'หลังชำระเงิน ให้โทร call center พร้อมแจ้ง order number เพื่อเลือกวันและเวลานัดตรวจ',
      'mock-product-pkg-cancer-baseline-evidence',
      'cancer',
      0.04
    ),
    (
      'd3e8c7a4-9a2b-4f66-c444-5ea8f6a0c303'::uuid,
      'pkg_executive_full',
      'Executive Longevity Check',
      'Mira Partner Hospital',
      'wellness',
      24900,
      'Full day',
      'Bangkok',
      'Wireless Road Life Science Center, Bangkok',
      'Mira Partner Hospital Wireless Road Bangkok',
      13.7359,
      100.5471,
      'แพ็กเกจตรวจสุขภาพเชิงลึกสำหรับ longevity, optimization และ trend tracking รวม advanced blood biomarkers, inflammation markers, hormone panel, nutrition และ sleep review โดยต้องแปลผลร่วมกับแพทย์',
      array['Advanced blood biomarkers', 'Inflammation markers', 'Hormone panel', 'Nutrition and sleep review'],
      array['Longevity', 'Hormone', 'Inflammation', 'CRP', 'wellness', 'ฮอร์โมน', 'ตรวจเชิงลึก', 'sleep'],
      'ยืนยัน fasting/timing กับโรงพยาบาล เพราะบาง biomarker หรือ hormone test อาจขึ้นกับเวลา ยา อาหารเสริม รอบเดือน การออกกำลัง แอลกอฮอล์ การนอน และการเจ็บป่วยล่าสุด',
      'หลังชำระเงิน ให้โทร call center พร้อมแจ้ง order number เพื่อเลือกวันและเวลานัดตรวจ',
      'mock-product-pkg-executive-full-evidence',
      'longevity',
      0.05
    )
)
insert into public.hospital_products (
  id,
  hospital_name,
  title,
  description,
  category,
  price_amount,
  currency,
  duration,
  location,
  hospital_address,
  hospital_map_query,
  hospital_lat,
  hospital_lng,
  includes,
  tags,
  preparation_notes,
  booking_note,
  status,
  rag_chunk_id,
  auto_category_confidence,
  metadata,
  created_by,
  created_at,
  updated_at
)
select
  seed_products.id,
  seed_products.hospital_name,
  seed_products.title,
  seed_products.description,
  seed_products.category,
  seed_products.price_amount,
  'THB',
  seed_products.duration,
  seed_products.location,
  seed_products.hospital_address,
  seed_products.hospital_map_query,
  seed_products.hospital_lat,
  seed_products.hospital_lng,
  seed_products.includes,
  seed_products.tags,
  seed_products.preparation_notes,
  seed_products.booking_note,
  'active',
  seed_products.rag_chunk_id,
  0.92,
  jsonb_build_object(
    'mock_package_id',
    seed_products.mock_package_id,
    'preview_image_key',
    seed_products.preview_image_key,
    'seed_source',
    'services/mockBackend.healthPackages',
    'rag_seeded_from',
    seed_products.rag_chunk_id,
    'gp_rate',
    0.05,
    'commission_rate',
    seed_products.referral_rate,
    'referral_rate',
    seed_products.referral_rate
  ),
  null,
  now(),
  now()
from seed_products
where not exists (
  select 1
  from public.hospital_products existing
  where lower(existing.title) = lower(seed_products.title)
    and lower(existing.hospital_name) = lower(seed_products.hospital_name)
)
on conflict (id) do update
set
  hospital_name = excluded.hospital_name,
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  price_amount = excluded.price_amount,
  currency = excluded.currency,
  duration = excluded.duration,
  location = excluded.location,
  hospital_address = excluded.hospital_address,
  hospital_map_query = excluded.hospital_map_query,
  hospital_lat = excluded.hospital_lat,
  hospital_lng = excluded.hospital_lng,
  includes = excluded.includes,
  tags = excluded.tags,
  preparation_notes = excluded.preparation_notes,
  booking_note = excluded.booking_note,
  status = excluded.status,
  rag_chunk_id = excluded.rag_chunk_id,
  auto_category_confidence = excluded.auto_category_confidence,
  metadata = excluded.metadata,
  updated_at = now();
